<a href="https://colab.research.google.com/github/Shubhranshu-Malhotra/Tensorflow-Developer-ZTM/blob/main/00_tf_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Fundmental concepts of tensor using Tensorflow
*  Introduction to Tensors
*  Getting information from tensors
*  Manipulating Tensors
*  Tensors & NumPy
*  Using `@tf.function`(a way to speed up regular Python functions)
*  Using GPU with TensorFlow (and TPU)
*  Exercises

## Introduction to Tensors

In [2]:
# Import TensorFlow
import tensorflow as tf
tf.__version__

'2.4.1'

### Create tensors with `tf.constant()`

In [3]:
# Create tensors with `tf.constant()`
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [4]:
 # Check number of dimensions of a tensor (ndim)
 scalar.ndim

0

In [5]:
# Create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [6]:
# Check dimensions of vector
vector.ndim

1

In [7]:
# Create a matrix (>1 dimensions)
matrix = tf.constant([[7,10],
                      [10,7]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7, 10],
       [10,  7]], dtype=int32)>

In [9]:
# Check dimensions for matrix 
matrix.ndim

2

In [14]:
# Create another matrix with `dtype` specified
another_matrix = tf.constant([[7.,10.],
                              [10.,7.],
                              [30.,100.]], dtype = 'float16')
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[  7.,  10.],
       [ 10.,   7.],
       [ 30., 100.]], dtype=float16)>

In [15]:
another_matrix.ndim

2

In [18]:
# Create a tensor
tensor = tf.constant([[[1,2,3],
                       [4,5,6]],
                      [[7,8,9],
                       [10,11,12]],
                      [[13,14,15],
                       [16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [20]:
# Number of dimensions in tensor
tensor.ndim

3

### Summary [Till Now]
*  Scalar: a single number
*  Vector: a number with a direction (eg wind speed and direction)
*  Matrix: a 2-dimensional array of numbers.
*  Tensor: an n-dimensional array of numbers. (where n can be any number, a 0-D tensor is a scalar, a 1-D tensor is a vector and a 2-D vector is a matrix)

### Tensors using `tf.Variable()`

In [23]:
# Create a changeable and unchangeable tensor
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [26]:
# try changing an element in `changeable_tensor`
# changeable_tensor[0] = 7  # The Wrong Way
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [31]:
# # `unchangeable_tensor` cannot be changed
# unchangeable_tensor[0] = 7 # Wrong
# unchangeable_tensor[0].assign(7) # Wrong

### Creating random tensors